# Law, Order, and Algorithms
## Introduction to `tidyverse`

In [1]:
# Some initial setup
options(digits = 3, repr.matrix.max.rows = 6)

In this section, and throughout most of the course, we will be using packages that are part of the [`tidyverse`](https://www.tidyverse.org/).

In [2]:
# First, we load the library
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ dplyr   1.0.0
✔ tidyr   1.1.0     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

The [tidyverse](https://www.tidyverse.org) is a collection of actively developed `R` packages that follow a certain principle of writing code.
Here, we will primarily focus on `dplyr`, which is the part of `tidyverse` which deals with data manipulation.

First, we will start by reading some data. 
There are many functions in `tidyverse` (and `R` in general) for reading various data formats into the `R` environment as a table of data (or, `data.frame`).
For example, either `read_csv` (from `tidyverse`) or `read.csv` (base `R`) can be used to read a `csv` file (e.g., a file where each line represents a row in the table, and the columns are separated by a `,`).

For this course, we have prepared a table of data in the `rds` format, a format that `R` uses to efficiently store data.
We can read the `sqf_sample.rds` file into the current `R` session with the `read_rds` function.
Let's name this table `stop_df`.

In [3]:
# Read the data
stop_df <- read_rds("../data/sqf_sample.rds")

Before getting started, we're going to do some light cleaning of the dataset, which will make it easier to work with. (Later in the exercise, we'll learn about what this line of code is doing.)

In [4]:
# transform the character vector 'hour' to numbers
stop_df <- mutate(stop_df, hour = parse_number(hour))

### The data

The loaded data frame, `stop_df`, is a sample of stops in NYC, recorded on a 
[UF-250 form][uf250_link]. (We consider a random sample of 1M stops out of a total of 3.8M in the full dataset.)

Each row corresponds to a stop that an officer made, and the columns represent various entries in the [UF-250 form][uf250_link].


Below is a list of columns in the data, roughly corresponding to the [UF-250 form][uf250_link]:

* Base information regarding stop:
    * `id`, `serial`, `year`, `date`, `day`, `time`, `hour`, `precinct`, `location_housing`, 
      `suspected_crime`, `lat`, `lon`, `xcoord`, `ycoord`

* Circumstances which led to the stop:
    * `stopped_bc_object`, `stopped_bc_desc`, `stopped_bc_casing`, `stopped_bc_lookout`, `stopped_bc_clothing`, `stopped_bc_drugs`, `stopped_bc_furtive`, `stopped_bc_violent`, `stopped_bc_bulge`, `stopped_bc_other`
    
* Suspect demographics:
    * `suspect_dob`, `suspect_id_type`, `suspect_sex`, `suspect_race`,
      `suspect_hispanic`, `suspect_age`, `suspect_height`, `suspect_weight`,
      `suspect_hair`, `suspect_eye`, `suspect_build`, `reason_explained`,
      `others_stopped`

* Whether physical force was used:
    * `force_hands`, `force_wall`, `force_ground`, `force_drawn`,
      `force_pointed`, `force_baton`, `force_handcuffs`,
      `force_pepper`, `force_other`

* Was suspect arrested?: `arrested`
    * if yes: `arrested_reason`

* Was summons issued?: `summons_issued`

* Officer in uniform?: `officer_uniform`, `officer_verbal`, `officer_shield`

* Was person frisked?: `frisked`
    * if yes: `frisked_bc_suspected_crime`, `frisked_bc_weapons`, `frisked_bc_attire`, `frisked_bc_actual_crime`, `frisked_bc_noncompliance`, `frisked_bc_threats`, `frisked_bc_prior`, `frisked_bc_furtive`, `frisked_bc_bulge`

* Was person searched?: `searched`,
    * if yes: `searched_hardobject`, `searched_outline`,
      `searched_admission`, `searched_other`

* Was weapon found?: `found_weapon`
    * if yes: `found_gun`, `found_pistol`, `found_rifle`, `found_assault`,
      `found_knife`, `found_machinegun`, `found_other`
      
* Was other contraband found?: `found_contraband`

* Additional circumstances/factors
    * `additional_report`, `additional_investigation`, `additional_proximity`, 
      `additional_evasive`, `additional_associating`, `additional_direction`, 
      `additional_highcrime`, `additional_time`, `additional_sights`, 
      `additional_other`

* Additional reports prepared: `extra_reports`

* Whether the stop was a resultof a radio run: `radio_run`

* Was the stop made inside or outside: `inside_outside`

* Period of observation (minutes): `observation_period`, `stop_length`

* Type of ID the person had (photo, refused, verified, other): `identification`

* Local hit rate: `local_hit_rate`, defined as the average hit rate for drug and cpw stops at the location of the stop for the previous year, using gaussian kernel averaging. NA if it's other type of stops.

[uf250_link]: https://www.prisonlegalnews.org/media/publications/Blank%20UF-250%20Form%20-%20Stop%2C%20Question%20and%20Frisk%20Report%20Worksheet%2C%20NYPD%2C%202016.pdf

We can also use some base `R` functions to explore the data.

### Exercise: understanding the data

Run `str(stop_df)` and `summary(stop_df)`.
Compare the output to the **UF-250 form** and the column descriptions above.
The goal is to understand what each column means, and how that information is stored (e.g., numbers, strings, logical values)

In [5]:
# WRITE CODE HERE
# START solution
str(stop_df)
summary(stop_df)
# END solution

tibble [1,000,000 × 93] (S3: tbl_df/tbl/data.frame)
 $ id                        : int [1:1000000] 597038 2229402 3498906 2572112 180901 3252586 2425502 238420 1131593 3146391 ...
 $ year                      : int [1:1000000] 2008 2011 2013 2011 2007 2012 2011 2007 2009 2012 ...
 $ frisked                   : logi [1:1000000] TRUE TRUE TRUE FALSE FALSE TRUE ...
 $ searched                  : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ xcoord                    : int [1:1000000] 1053946 1040970 NA 999065 1008532 1012212 1005688 1007890 1004980 1010354 ...
 $ ycoord                    : int [1:1000000] 197411 188491 NA 229913 190147 179425 180555 191462 234079 170483 ...
 $ date                      : Date[1:1000000], format: "2008-03-16" "2011-01-20" ...
 $ time                      : chr [1:1000000] "21:15" "02:10" "01:45" "16:08" ...
 $ hour                      : num [1:1000000] 21 2 1 16 0 8 20 15 18 16 ...
 $ precinct                  : Factor w/ 77 levels "1","10","100",..: 8 16 46 30 72 66 58 72 39 60 ...
 $ serial                    : int [1:1000000] 1504 391 1973 12384 3123 18558 3642 3968 4202 2431 ...
 $ radio_run                 : logi [1:1000000] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ inside_outside            : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE TRUE ...
 $ location_housing          : Factor w/ 3 levels "neither","housing",..: 1 1 1 2 1 3 1 1 2 1 ...
 $ observation_period        : num [1:1000000] 1 1 1 2 1 10 5 1 1 1 ...
 $ suspected_crime           : chr [1:1000000] "robbery" "cpw" "cpw" "criminal possession of marihuana" ...
 $ stop_length               : int [1:1000000] 5 1 5 4 2 3 5 7 2 5 ...
 $ identification            : Factor w/ 4 levels "other","photo",..: 2 4 2 2 4 4 4 4 2 4 ...
 $ reason_explained          : logi [1:1000000] TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ others_stopped            : logi [1:1000000] TRUE FALSE TRUE FALSE FALSE TRUE ...
 $ arrested                  : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ arrested_reason           : Factor w/ 26 levels "assault","burglary",..: NA NA NA NA NA NA NA NA NA NA ...
 $ summons_issued            : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ officer_uniform           : logi [1:1000000] FALSE FALSE FALSE TRUE TRUE FALSE ...
 $ officer_verbal            : logi [1:1000000] TRUE TRUE TRUE NA NA NA ...
 $ officer_shield            : logi [1:1000000] TRUE TRUE TRUE NA NA TRUE ...
 $ extra_reports             : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_hands               : logi [1:1000000] TRUE TRUE FALSE FALSE FALSE FALSE ...
 $ force_wall                : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_ground              : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_drawn               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_pointed             : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_baton               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_handcuffs           : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_pepper              : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ force_other               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_object         : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_desc           : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_casing         : logi [1:1000000] TRUE TRUE FALSE FALSE TRUE TRUE ...
 $ stopped_bc_lookout        : logi [1:1000000] TRUE TRUE FALSE FALSE FALSE TRUE ...
 $ stopped_bc_clothing       : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_drugs          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_furtive        : logi [1:1000000] TRUE TRUE TRUE TRUE FALSE TRUE ...
 $ stopped_bc_violent        : logi [1:1000000] FALSE TRUE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_bulge          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ stopped_bc_other          : logi [1:1000000] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ frisked_bc_suspected_crime: logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_weapons        : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_attire         : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_actual_crime   : logi [1:1000000] FALSE TRUE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_noncompliance  : logi [1:1000000] TRUE FALSE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_threats        : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_prior          : logi [1:1000000] FALSE TRUE FALSE FALSE FALSE FALSE ...
 $ frisked_bc_furtive        : logi [1:1000000] FALSE TRUE TRUE FALSE FALSE TRUE ...
 $ frisked_bc_bulge          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_report         : logi [1:1000000] FALSE FALSE FALSE FALSE TRUE FALSE ...
 $ additional_investigation  : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_proximity      : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_evasive        : logi [1:1000000] TRUE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_associating    : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_direction      : logi [1:1000000] TRUE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_highcrime      : logi [1:1000000] TRUE FALSE TRUE TRUE FALSE FALSE ...
 $ additional_time           : logi [1:1000000] TRUE FALSE TRUE TRUE FALSE FALSE ...
 $ additional_sights         : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ additional_other          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ searched_hardobject       : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ searched_outline          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ searched_admission        : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ searched_other            : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_contraband          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_pistol              : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_rifle               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_assault             : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_knife               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_machinegun          : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_other               : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ suspect_sex               : Factor w/ 2 levels "male","female": 1 1 1 1 1 1 NA 1 1 1 ...
 $ suspect_race              : Factor w/ 6 levels "asian","black",..: 2 2 2 4 4 2 6 4 4 2 ...
 $ suspect_hispanic          : logi [1:1000000] FALSE FALSE FALSE TRUE TRUE FALSE ...
 $ suspect_age               : int [1:1000000] 23 30 35 28 27 14 31 21 32 24 ...
 $ suspect_dob               : chr [1:1000000] "1984-05-31" NA NA NA ...
 $ suspect_height            : num [1:1000000] 5.92 5.83 5.42 5.67 5.75 ...
 $ suspect_weight            : int [1:1000000] 185 180 160 170 140 115 180 180 170 170 ...
 $ suspect_hair              : Factor w/ 13 levels "bald","black",..: 2 2 2 5 2 2 2 4 2 2 ...
 $ suspect_eye               : Factor w/ 12 levels "black","blue",..: 3 3 1 3 3 3 3 3 3 3 ...
 $ suspect_build             : Factor w/ 5 levels "heavy","medium",..: 3 2 2 2 3 2 2 2 2 2 ...
 $ found_gun                 : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ found_weapon              : logi [1:1000000] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lat                       : num [1:1000000] 40.7 40.7 NA 40.8 40.7 ...
 $ lon                       : num [1:1000000] -73.7 -73.8 NA -73.9 -73.9 ...
 $ local_hit_rate            : num [1:1000000] NA 0.0229 NA 0.0929 NA ...
 $ day                       : Ord.factor w/ 7 levels "Sunday"<"Monday"<..: 1 5 3 6 7 5 7 4 2 2 ...
 $ month                     : Ord.factor w/ 12 levels "January"<"February"<..: 3 1 3 8 5 8 4 6 3 5 ...

       id               year       frisked         searched
 Min.   :      1   Min.   :2007   Mode :logical   Mode :logical
 1st Qu.: 903491   1st Qu.:2008   FALSE:444857    FALSE:911528
 Median :1802222   Median :2010   TRUE :555143    TRUE :88472
 Mean   :1803220   Mean   :2010
 3rd Qu.:2704923   3rd Qu.:2011
 Max.   :3605334   Max.   :2013

     xcoord            ycoord            date                time
 Min.   : 913367   Min.   :121061   Min.   :1900-12-31   Length:1000000
 1st Qu.: 996546   1st Qu.:183216   1st Qu.:2008-10-19   Class :character
 Median :1005485   Median :198380   Median :2010-04-30   Mode  :character
 Mean   :1006448   Mean   :204566   Mean   :2010-04-02
 3rd Qu.:1016926   3rd Qu.:231877   3rd Qu.:2011-09-28
 Max.   :1067249   Max.   :271730   Max.   :2013-12-31
 NA's   :30976     NA's   :30976    NA's   :326
      hour        precinct          serial      radio_run       inside_outside
 Min.   : 0    75     : 47823   Min.   :    1   Mode :logical   Mode :logical
 1st Qu.: 9    73     : 40461   1st Qu.: 1747   FALSE:759178    FALSE:771745
 Median :16    79     : 30255   Median : 3869   TRUE :240822    TRUE :228255
 Mean   :14    120    : 28299   Mean   : 5254
 3rd Qu.:20    40     : 27129   3rd Qu.: 7284
 Max.   :23    23     : 26134   Max.   :31759
 NA's   :326   (Other):799899
 location_housing observation_period suspected_crime     stop_length
 neither:772536   Min.   :  0        Length:1000000     Min.   :  0
 housing:150712   1st Qu.:  1        Class :character   1st Qu.:  3
 transit: 76752   Median :  1        Mode  :character   Median :  5
                  Mean   :  3                           Mean   :  6
                  3rd Qu.:  2                           3rd Qu.:  5
                  Max.   :999                           Max.   :999
                                                        NA's   :94
 identification   reason_explained others_stopped   arrested
 other  : 14202   Mode :logical    Mode :logical   Mode :logical
 photo  :545987   FALSE:821        FALSE:794436    FALSE:937769
 refused: 17648   TRUE :999179     TRUE :205564    TRUE :62231
 verbal :422163



                                    arrested_reason   summons_issued
 not.top.100                                : 22229   Mode :logical
 criminal possession of marihuana           :  7711   FALSE:937854
 cpw                                        :  6661   TRUE :62146
 criminal trespass                          :  6443
 criminal possession of controlled substance:  4414
 (Other)                                    : 14735
 NA's                                       :937807
 officer_uniform officer_verbal  officer_shield  extra_reports
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:274551    FALSE:1200      FALSE:977       FALSE:999336
 TRUE :725448    TRUE :211706    TRUE :270933    TRUE :664
 NA's :1         NA's :787094    NA's :728090



 force_hands     force_wall      force_ground    force_drawn
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:811517    FALSE:968659    FALSE:996057    FALSE:997976
 TRUE :188483    TRUE :31341     TRUE :3943      TRUE :2024




 force_pointed   force_baton     force_handcuffs force_pepper
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:997063    FALSE:999863    FALSE:964730    FALSE:999831
 TRUE :2937      TRUE :137       TRUE :35270     TRUE :169




 force_other     stopped_bc_object stopped_bc_desc stopped_bc_casing
 Mode :logical   Mode :logical     Mode :logical   Mode :logical
 FALSE:995262    FALSE:974456      FALSE:835107    FALSE:691786
 TRUE :4738      TRUE :25544       TRUE :164893    TRUE :308214




 stopped_bc_lookout stopped_bc_clothing stopped_bc_drugs stopped_bc_furtive
 Mode :logical      Mode :logical       Mode :logical    Mode :logical
 FALSE:823934       FALSE:953699        FALSE:913660     FALSE:515820
 TRUE :176066       TRUE :46301         TRUE :86340      TRUE :484180




 stopped_bc_violent stopped_bc_bulge stopped_bc_other
 Mode :logical      Mode :logical    Mode :logical
 FALSE:907538       FALSE:911625     FALSE:818046
 TRUE :92462        TRUE :88375      TRUE :181954




 frisked_bc_suspected_crime frisked_bc_weapons frisked_bc_attire
 Mode :logical              Mode :logical      Mode :logical
 FALSE:878265               FALSE:962350       FALSE:920441
 TRUE :121735               TRUE :37650        TRUE :79559




 frisked_bc_actual_crime frisked_bc_noncompliance frisked_bc_threats
 Mode :logical           Mode :logical            Mode :logical
 FALSE:931016            FALSE:909858             FALSE:994171
 TRUE :68984             TRUE :90142              TRUE :5829




 frisked_bc_prior frisked_bc_furtive frisked_bc_bulge additional_report
 Mode :logical    Mode :logical      Mode :logical    Mode :logical
 FALSE:985085     FALSE:624058       FALSE:915264     FALSE:877227
 TRUE :14915      TRUE :375942       TRUE :84736      TRUE :122773




 additional_investigation additional_proximity additional_evasive
 Mode :logical            Mode :logical        Mode :logical
 FALSE:867308             FALSE:794750         FALSE:802993
 TRUE :132692             TRUE :205250         TRUE :197007




 additional_associating additional_direction additional_highcrime
 Mode :logical          Mode :logical        Mode :logical
 FALSE:960194           FALSE:751539         FALSE:427815
 TRUE :39806            TRUE :248461         TRUE :572185




 additional_time additional_sights additional_other searched_hardobject
 Mode :logical   Mode :logical     Mode :logical    Mode :logical
 FALSE:602902    FALSE:975672      FALSE:962750     FALSE:954880
 TRUE :397098    TRUE :24328       TRUE :37250      TRUE :45120




 searched_outline searched_admission searched_other  found_contraband
 Mode :logical    Mode :logical      Mode :logical   Mode :logical
 FALSE:994051     FALSE:996789       FALSE:961442    FALSE:980543
 TRUE :5949       TRUE :3211         TRUE :38558     TRUE :18057
                                                     NA's :1400



 found_pistol    found_rifle     found_assault   found_knife
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:998764    FALSE:999948    FALSE:999903    FALSE:991533
 TRUE :1236      TRUE :52        TRUE :97        TRUE :8467




 found_machinegun found_other     suspect_sex              suspect_race
 Mode :logical    Mode :logical   male  :913163   asian          : 31781
 FALSE:999989     FALSE:997471    female: 69514   black          :522449
 TRUE :11         TRUE :2529      NA's  : 17323   native american:  4015
                                                  hispanic       :311440
                                                  white          : 98077
                                                  other          : 26082
                                                  NA's           :  6156
 suspect_hispanic  suspect_age   suspect_dob        suspect_height
 Mode :logical    Min.   :10.0   Length:1000000     Min.   :3.00
 FALSE:688560     1st Qu.:19.0   Class :character   1st Qu.:5.58
 TRUE :311440     Median :24.0   Mode  :character   Median :5.75
                  Mean   :28.1                      Mean   :5.72
                  3rd Qu.:34.0                      3rd Qu.:5.92
                  Max.   :80.0                      Max.   :7.92

 suspect_weight  suspect_hair     suspect_eye      suspect_build
 Min.   :  0    black  :749325   brown  :893387   heavy   : 82897
 1st Qu.:150    brown  :197041   black  : 66271   medium  :593698
 Median :170    bald   : 15913   blue   : 17112   thin    :309238
 Mean   :169    blond  : 12242   green  :  6993   muscular:  3764
 3rd Qu.:180    gray   :  9156   hazel  :  6484   unknown : 10403
 Max.   :918    (Other): 15185   unknown:  4892
 NA's   :807    NA's   :  1138   (Other):  4861
 found_gun       found_weapon         lat             lon
 Mode :logical   Mode :logical   Min.   :40      Min.   :-74
 FALSE:998634    FALSE:988185    1st Qu.:41      1st Qu.:-74
 TRUE :1366      TRUE :11815     Median :41      Median :-74
                                 Mean   :41      Mean   :-74
                                 3rd Qu.:41      3rd Qu.:-74
                                 Max.   :41      Max.   :-74
                                 NA's   :30976   NA's   :30976
 local_hit_rate          day              month
 Min.   :0        Friday   :169863   January :105692
 1st Qu.:0        Saturday :159063   March   : 99247
 Median :0        Wednesday:157272   February: 97315
 Mean   :0        Thursday :156782   April   : 93946
 3rd Qu.:0        Tuesday  :143278   May     : 90132
 Max.   :1        (Other)  :213416   (Other) :513342
 NA's   :770813   NA's     :   326   NA's    :   326

### Exercise: Extracting columns

Let's get a better sense of the demographic composition of stops. To do this, we'll be dealing with the `suspect_race` column in our dataframe.

There are two ways to extract race from our `stop_df` dataframe: `stop_df$suspect_race` and `pull(stop_df, suspect_race)`. Basically,`$` and `pull()` do the same thing.

  1.  Check `length(stop_df$suspect_race)` (or, equivalently, `length(pull(stop_df, suspect_race))`). Since this vector is too long to print, try instead _sampling_ a few entries from it using `sample()`, just like we did last time.

  2.  How many stops are recorded for each group? (Hint: apply the `table` function to the `suspect_race` column.)

In [6]:
## EXERCISE 1: YOUR CODE HERE
# START
# 1. 
# We get a list of the date each stop occurred on. 
# Both methods ($ and pull) do the same thing, they
# extract the column `date` from the df.
length(stop_df$suspect_race)
sample(stop_df$suspect_race, 10)

# 2. 
table(stop_df$suspect_race)
# END

[1] 1000000

 [1] black    hispanic other    black    hispanic black    white    hispanic
 [9] hispanic hispanic
Levels: asian black native american hispanic white other

          asian           black native american        hispanic           white
          31781          522449            4015          311440           98077
          other
          26082

## Introduction to `dplyr` verbs

In the world of `dplyr`, a _verb_ is a function that

* takes a data frame as its first argument, and
* returns another data frame as a result

Any function that meets this criterion, even if it's not necessarily a function in the `dplyr` package, can be considered a _verb_.

For example, the `head()` function in `R`, if applied to a data frame, will return a first `n` rows of a data frame.

In [7]:
head(stop_df, n = 3)  # Return a data frame that consists of the first three rows of stop_df

  id      year frisked searched xcoord  ycoord date       time  hour precinct ⋯
1  597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21   105      ⋯
2 2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2   113      ⋯
3 3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1   47       ⋯
  suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1 black        brown       thin          FALSE     FALSE        40.7 -73.7
2 black        brown       medium        FALSE     FALSE        40.7 -73.8
3 black        black       medium        FALSE     FALSE          NA    NA
  local_hit_rate day      month
1     NA         Sunday   March
2 0.0229         Thursday January
3     NA         Tuesday  March

In this sense, the base `R` function `head()` is a verb.

The **core idea** of `dplyr` is that a vast majority of data manipulation needs can be satisfied through a combination of five verbs.

verb                 | action
-------------------- | ---------
`filter(df, ...)`    | select a subset of _rows_ by some specified condition
`select(df, ...)`    | select a subset of _columns_
`mutate(df, ...)`    | create a _new column_ (often as a function of existing columns)
`arrange(df, ...)`   | reorder (sort) _rows_ according to values of specific _columns_
`summarize(df, ...)` | aggregate and reduce a vector (column) to a single value

We will explore each of these verbs (and some additional variations within each category) below.

### Selecting rows (1/5)

The `filter(df, ...)` verb is used to select a subset of _rows_ that satisfy the conditions specified in `...`. 
The conditions must be written in a form that would evaluate to either `TRUE` or `FALSE`.

For example, if we want a data frame of stops in precinct `22`,

In [8]:
filter(stop_df, precinct == 22)

     id      year frisked searched xcoord ycoord date       time  hour precinct
1     788795 2008  TRUE   FALSE    990508 220370 2008-08-03 08:35  8   22
2     318768 2007 FALSE   FALSE    992274 223433 2007-08-29 12:58 12   22
3    2569541 2011 FALSE   FALSE    991301 219724 2011-08-27 12:13 12   22
⋮    ⋮       ⋮    ⋮       ⋮        ⋮      ⋮      ⋮          ⋮     ⋮    ⋮
1562 1900884 2010 FALSE   FALSE    994617 227693 2010-06-23 08:40  8   22
1563 1500666 2009  TRUE   FALSE        NA     NA 2009-10-21 22:00 22   22
1564  126805 2007 FALSE   FALSE    993329 225084 2007-03-26 16:05 16   22
     ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1    ⋯ black        brown       medium        FALSE     FALSE        40.8 -74
2    ⋯ black        brown       thin          FALSE     FALSE        40.8 -74
3    ⋯ black        brown       thin          FALSE     FALSE        40.8 -74
⋮    ⋱ ⋮            ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
1562 ⋯ black        brown       thin          FALSE     FALSE        40.8 -74
1563 ⋯ black        brown       medium        FALSE     FALSE          NA  NA
1564 ⋯ black        black       medium        FALSE     FALSE        40.8 -74
     local_hit_rate day       month
1        NA         Sunday    August
2        NA         Wednesday August
3    0.0788         Saturday  August
⋮    ⋮              ⋮         ⋮
1562 NA             Wednesday June
1563 NA             Wednesday October
1564 NA             Monday    March

Multiple conditions can also be specified.

For example, if we want a data frame of stops in precinct `22` in which a weapon was found,

In [9]:
filter(stop_df, precinct == 22, found_weapon)
# Note that we could also write
#   filter(stop_df, precinct == 22, found_weapon == TRUE)
# but given that the found_weapon column is already a logical value,
# the "== TRUE" would be redundant.

   id      year frisked searched xcoord ycoord date       time  hour precinct ⋯
1  2817889 2011 TRUE    TRUE     996048 226907 2011-11-25 19:50 19   22       ⋯
2  3543881 2013 TRUE    TRUE     993329 225084 2013-05-15 18:00 18   22       ⋯
3  3096503 2012 TRUE    TRUE     992274 223433 2012-05-13 15:00 15   22       ⋯
⋮  ⋮       ⋮    ⋮       ⋮        ⋮      ⋮      ⋮          ⋮     ⋮    ⋮        ⋱
8  3096549 2012 TRUE    FALSE    996048 226907 2012-06-19 17:15 17   22       ⋯
9  3537210 2013 TRUE     TRUE    993538 222793 2013-05-05 19:30 19   22       ⋯
10 2569665 2011 TRUE     TRUE    993538 222793 2011-09-27 15:59 15   22       ⋯
   suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1  brown        brown       thin          FALSE     TRUE         40.8 -74
2  black        brown       thin          FALSE     TRUE         40.8 -74
3  black        brown       heavy         FALSE     TRUE         40.8 -74
⋮  ⋮            ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
8  black        brown       medium        FALSE     TRUE         40.8 -74
9  brown        brown       medium        FALSE     TRUE         40.8 -74
10 black        brown       medium        FALSE     TRUE         40.8 -74
   local_hit_rate day       month
1  0.0230         Friday    November
2      NA         Wednesday May
3  0.0836         Sunday    May
⋮  ⋮              ⋮         ⋮
8  0.0163         Tuesday   June
9      NA         Sunday    May
10     NA         Tuesday   September

By default, `filter()` will combine multiple conditions as `AND` operations.
In the example above, we are returned stops where `precinct == 22` _**AND**_ `found_weapon == TRUE`.

We can specify an OR condition by using the `|` operator.

For example, if we want stops in precinct `22` where either a weapon _**OR**_ contraband was found,

In [10]:
filter(stop_df, 
       precinct == 22, 
       found_weapon | found_contraband)

# Note that, within a set of parentheses, you can have as many line breaks as you want.
# It's generally easier to read (and modify) if you have each condition on a new line.
# For example, if you quickly wanted to check what the result looks like for _all_ precincts,
# in the above code, you could just "comment out" the precinct == 22 condition by adding a "#" at the begining of the line

   id      year frisked searched xcoord ycoord date       time  hour precinct ⋯
1  2324151 2011 FALSE   FALSE        NA     NA 2011-03-05 13:50 13   22       ⋯
2  1012484 2009 FALSE   FALSE    990508 220370 2009-01-01 00:15  0   22       ⋯
3  2569542 2011  TRUE   FALSE    993329 225084 2011-08-23 19:29 19   22       ⋯
⋮  ⋮       ⋮    ⋮       ⋮        ⋮      ⋮      ⋮          ⋮     ⋮    ⋮        ⋱
39  708198 2008 FALSE   FALSE    992831 221040 2008-05-28 13:10 13   22       ⋯
40 2398699 2011 FALSE   FALSE        NA     NA 2011-04-10 17:12 17   22       ⋯
41 2569665 2011  TRUE    TRUE    993538 222793 2011-09-27 15:59 15   22       ⋯
   suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1  gray         black       medium        FALSE     FALSE          NA  NA
2  blond        black       thin          FALSE     FALSE        40.8 -74
3  black        brown       thin          FALSE     FALSE        40.8 -74
⋮  ⋮            ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
39 black        brown       medium        FALSE     FALSE        40.8 -74
40 black        brown       medium        FALSE     FALSE          NA  NA
41 black        brown       medium        FALSE      TRUE        40.8 -74
   local_hit_rate day       month
1      NA         Saturday  March
2      NA         Thursday  January
3  0.0972         Tuesday   August
⋮  ⋮              ⋮         ⋮
39 NA             Wednesday May
40 NA             Sunday    April
41 NA             Tuesday   September

Use the `%in%` operator to filter to values that match a collection of values. 

For example, suppose we are primarily interested in `burglary`, `robbery`, and `grand larceny`.

In [11]:
filter(stop_df, 
       suspected_crime %in% c("burglary", "robbery", "grand larceny"))

       id      year frisked searched xcoord  ycoord date       time  hour
1       597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2      3252586 2012 TRUE    FALSE    1012212 179425 2012-08-02 08:42  8
3      3146391 2012 TRUE    FALSE    1010354 170483 2012-05-07 16:40 16
⋮      ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
319658 2894756 2012 FALSE   FALSE    1007520 224651 2012-01-07 21:35 21
319659 3549306 2013  TRUE   FALSE    1032641 217298 2013-05-22 10:51 10
319660 2840524 2011  TRUE   FALSE    1017479 181524 2011-12-08 00:10  0
       precinct ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon
1      105      ⋯ black        brown       thin          FALSE     FALSE
2      75       ⋯ black        brown       medium        FALSE     FALSE
3      69       ⋯ black        brown       medium        FALSE     FALSE
⋮      ⋮        ⋱ ⋮            ⋮           ⋮             ⋮         ⋮
319658 114      ⋯ black        black       thin          FALSE     FALSE
319659 109      ⋯ black        brown       thin          FALSE     FALSE
319660 75       ⋯ brown        brown       thin          FALSE     FALSE
       lat  lon   local_hit_rate day       month
1      40.7 -73.7 NA             Sunday    March
2      40.7 -73.9 NA             Thursday  August
3      40.6 -73.9 NA             Monday    May
⋮      ⋮    ⋮     ⋮              ⋮         ⋮
319658 40.8 -73.9 NA             Saturday  January
319659 40.8 -73.8 NA             Wednesday May
319660 40.7 -73.9 NA             Thursday  December

As a side note, the preferred way of writing the above filter would be to first create a vector of the crimes that we are interested in.
That way, it's easier for us to: (1) understand the code; and (2) change the code later, e.g., if we decide we're interested in different type of crime.

In [12]:
interesting_crimes <- c("burglary", "robbery", "grand larceny")

filter(stop_df, 
       suspected_crime %in% interesting_crimes)

       id      year frisked searched xcoord  ycoord date       time  hour
1       597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2      3252586 2012 TRUE    FALSE    1012212 179425 2012-08-02 08:42  8
3      3146391 2012 TRUE    FALSE    1010354 170483 2012-05-07 16:40 16
⋮      ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
319658 2894756 2012 FALSE   FALSE    1007520 224651 2012-01-07 21:35 21
319659 3549306 2013  TRUE   FALSE    1032641 217298 2013-05-22 10:51 10
319660 2840524 2011  TRUE   FALSE    1017479 181524 2011-12-08 00:10  0
       precinct ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon
1      105      ⋯ black        brown       thin          FALSE     FALSE
2      75       ⋯ black        brown       medium        FALSE     FALSE
3      69       ⋯ black        brown       medium        FALSE     FALSE
⋮      ⋮        ⋱ ⋮            ⋮           ⋮             ⋮         ⋮
319658 114      ⋯ black        black       thin          FALSE     FALSE
319659 109      ⋯ black        brown       thin          FALSE     FALSE
319660 75       ⋯ brown        brown       thin          FALSE     FALSE
       lat  lon   local_hit_rate day       month
1      40.7 -73.7 NA             Sunday    March
2      40.7 -73.9 NA             Thursday  August
3      40.6 -73.9 NA             Monday    May
⋮      ⋮    ⋮     ⋮              ⋮         ⋮
319658 40.8 -73.9 NA             Saturday  January
319659 40.8 -73.8 NA             Wednesday May
319660 40.7 -73.9 NA             Thursday  December

Finally, use `!` to negate any condition. 

For example, if we wanted to find all stops where the suspected crime is _not_ one of the `interesting_crimes`,

In [13]:
filter(stop_df, 
       !(suspected_crime %in% interesting_crimes))

       id      year frisked searched xcoord  ycoord date       time  hour
1      2229402 2011  TRUE   FALSE    1040970 188491 2011-01-20 02:10  2
2      3498906 2013  TRUE   FALSE         NA     NA 2013-03-12 01:45  1
3      2572112 2011 FALSE   FALSE     999065 229913 2011-08-26 16:08 16
⋮      ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
680338  161090 2007 FALSE   FALSE    1013022 182527 2007-04-20 18:40 18
680339 3026282 2012  TRUE   FALSE    1003466 250306 2012-03-05 22:36 22
680340 2657973 2011  TRUE    TRUE    1003927 186763 2011-08-04 08:30  8
       precinct ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon
1      113      ⋯ black        brown       medium        FALSE     FALSE
2      47       ⋯ black        black       medium        FALSE     FALSE
3      23       ⋯ dyed         brown       medium        FALSE     FALSE
⋮      ⋮        ⋱ ⋮            ⋮           ⋮             ⋮         ⋮
680338 75       ⋯ black        brown       medium        FALSE     FALSE
680339 34       ⋯ black        brown       thin          FALSE     FALSE
680340 81       ⋯ black        brown       medium        FALSE     FALSE
       lat  lon   local_hit_rate day      month
1      40.7 -73.8 0.0229         Thursday January
2        NA    NA     NA         Tuesday  March
3      40.8 -73.9 0.0929         Friday   August
⋮      ⋮    ⋮     ⋮              ⋮        ⋮
680338 40.7 -73.9     NA         Friday   April
680339 40.9 -73.9 0.0366         Monday   March
680340 40.7 -73.9 0.0305         Thursday August

or, if you want to exclude stops in 2008

In [14]:
filter(stop_df, year != 2008)

       id      year frisked searched xcoord  ycoord date       time  hour
1      2229402 2011  TRUE   FALSE    1040970 188491 2011-01-20 02:10  2
2      3498906 2013  TRUE   FALSE         NA     NA 2013-03-12 01:45  1
3      2572112 2011 FALSE   FALSE     999065 229913 2011-08-26 16:08 16
⋮      ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
850374 2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
850375 3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
850376 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
       precinct ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon
1      113      ⋯ black        brown       medium        FALSE     FALSE
2      47       ⋯ black        black       medium        FALSE     FALSE
3      23       ⋯ dyed         brown       medium        FALSE     FALSE
⋮      ⋮        ⋱ ⋮            ⋮           ⋮             ⋮         ⋮
850374 75       ⋯ brown        brown       thin          FALSE     FALSE
850375 34       ⋯ black        brown       thin          FALSE     FALSE
850376 81       ⋯ black        brown       medium        FALSE     FALSE
       lat  lon   local_hit_rate day      month
1      40.7 -73.8 0.0229         Thursday January
2        NA    NA     NA         Tuesday  March
3      40.8 -73.9 0.0929         Friday   August
⋮      ⋮    ⋮     ⋮              ⋮        ⋮
850374 40.7 -73.9     NA         Thursday December
850375 40.9 -73.9 0.0366         Monday   March
850376 40.7 -73.9 0.0305         Thursday August

### Exercise: `filter()`

1. Find all the minority (non-white) race (`suspect_race`) stops which took place in transit (`location_housing == "transit"`), 
   where the suspected crime was criminal possession of a weapon (`cpw`) and a gun was eventually found (`found_gun`).
1. Find all stops that occurred in either 2008 _or_ 2011, in precinct 13, between midnight (`hour = 0`) and 2am, 
   where a weapon was not found.

In [15]:
# WRITE CODE HERE
# START solution
# 1. 
filter(stop_df, 
       suspect_race != "white",
       location_housing == "transit",
       suspected_crime == "cpw",
       found_gun)

# 2. 
filter(stop_df, 
       year %in% c(2008, 2011),
       precinct == 13,
       hour >= 0,
       hour <= 2,
       !found_weapon)
# END solution

   id      year frisked searched xcoord  ycoord date       time  hour precinct
1  466637  2007 TRUE    TRUE     1003927 186763 2007-12-26 12:40 12   81
2  669635  2008 TRUE    TRUE      984843 209263 2008-05-02 13:45 13   13
3  811977  2008 TRUE    TRUE     1012791 238814 2008-08-21 00:50  0   41
⋮  ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮    ⋮
13  839331 2008 TRUE     TRUE    1002584 248715 2008-09-10 18:10 18   34
14 1788813 2010 TRUE    FALSE     998181 231480 2010-04-24 01:10  1   28
15 3498396 2013 TRUE     TRUE    1002212 193214 2013-03-11 01:30  1   83
   ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1  ⋯ black        brown       heavy         TRUE      TRUE         40.7 -73.9
2  ⋯ black        brown       medium        TRUE      TRUE         40.7 -74.0
3  ⋯ black        brown       medium        TRUE      TRUE         40.8 -73.9
⋮  ⋱ ⋮            ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
13 ⋯ black        brown       medium        TRUE      TRUE         40.8 -73.9
14 ⋯ black        brown       thin          TRUE      TRUE         40.8 -73.9
15 ⋯ black        black       medium        TRUE      TRUE         40.7 -73.9
   local_hit_rate day       month
1  NA             Wednesday December
2  NA             Friday    May
3  NA             Thursday  August
⋮  ⋮              ⋮         ⋮
13     NA         Wednesday September
14 0.0316         Saturday  April
15     NA         Monday    March

    id      year frisked searched xcoord ycoord date       time  hour precinct
1    705797 2008 FALSE   FALSE    986244 209936 2008-05-26 02:11 2    13
2   2563235 2011  TRUE   FALSE    987522 210136 2011-09-16 01:06 1    13
3    659701 2008 FALSE   FALSE    985814 207859 2008-04-25 00:20 0    13
⋮   ⋮       ⋮    ⋮       ⋮        ⋮      ⋮      ⋮          ⋮     ⋮    ⋮
383 2316339 2011 FALSE   FALSE    989752 209484 2011-03-02 00:27 0    13
384  797859 2008 FALSE   FALSE    991139 207207 2008-08-10 02:00 2    13
385  994800 2008  TRUE   FALSE    986773 207520 2008-12-16 02:30 2    13
    ⋯ suspect_hair suspect_eye suspect_build found_gun found_weapon lat  lon
1   ⋯ black        brown       thin          FALSE     FALSE        40.7 -74
2   ⋯ brown        brown       thin          FALSE     FALSE        40.7 -74
3   ⋯ brown        brown       medium        FALSE     FALSE        40.7 -74
⋮   ⋱ ⋮            ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
383 ⋯ brown        brown       thin          FALSE     FALSE        40.7 -74
384 ⋯ brown        brown       medium        FALSE     FALSE        40.7 -74
385 ⋯ black        brown       thin          FALSE     FALSE        40.7 -74
    local_hit_rate day       month
1   NA             Monday    May
2   NA             Friday    September
3   NA             Friday    April
⋮   ⋮              ⋮         ⋮
383 NA             Wednesday March
384 NA             Sunday    August
385 NA             Tuesday   December

### Selecting columns (2/5)

Use `select(df, ...)` to either specify which columns to select,

In [16]:
select(stop_df, year, precinct, suspected_crime)

        year precinct suspected_crime
1       2008 105      robbery
2       2011 113      cpw
3       2013 47       cpw
⋮       ⋮    ⋮        ⋮
999998  2011 75       robbery
999999  2012 34       criminal possession of marihuana
1000000 2011 81       cpw

or to specify which columns to exclude, using `-`.

In [17]:
select(stop_df, -id, -year, -date, -time, -precinct, -location_housing)

        frisked searched xcoord  ycoord hour serial radio_run inside_outside
1       TRUE    FALSE    1053946 197411 21   1504   FALSE     FALSE
2       TRUE    FALSE    1040970 188491  2    391   FALSE     FALSE
3       TRUE    FALSE         NA     NA  1   1973   FALSE     FALSE
⋮       ⋮       ⋮        ⋮       ⋮      ⋮    ⋮      ⋮         ⋮
999998  TRUE    FALSE    1017479 181524  0   30680  FALSE     FALSE
999999  TRUE    FALSE    1003466 250306 22    2974  FALSE     FALSE
1000000 TRUE     TRUE    1003927 186763  8    8504   TRUE      TRUE
        observation_period suspected_crime                  ⋯ suspect_hair
1       1                  robbery                          ⋯ black
2       1                  cpw                              ⋯ black
3       1                  cpw                              ⋯ black
⋮       ⋮                  ⋮                                ⋱ ⋮
999998  3                  robbery                          ⋯ brown
999999  2                  criminal possession of marihuana ⋯ black
1000000 2                  cpw                              ⋯ black
        suspect_eye suspect_build found_gun found_weapon lat  lon
1       brown       thin          FALSE     FALSE        40.7 -73.7
2       brown       medium        FALSE     FALSE        40.7 -73.8
3       black       medium        FALSE     FALSE          NA    NA
⋮       ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
999998  brown       thin          FALSE     FALSE        40.7 -73.9
999999  brown       thin          FALSE     FALSE        40.9 -73.9
1000000 brown       medium        FALSE     FALSE        40.7 -73.9
        local_hit_rate day      month
1           NA         Sunday   March
2       0.0229         Thursday January
3           NA         Tuesday  March
⋮       ⋮              ⋮        ⋮
999998      NA         Thursday December
999999  0.0366         Monday   March
1000000 0.0305         Thursday August

`dplyr` also provides some useful helper functions to `select()` columns that match specific criteria.

* `starts_with(x)`: match column names that start with `x`
* `ends_with(x)`: match column names that end with `x`
* `contains(x)`: match column names that contain `x`
* `matches(x)`: match column names that match (the regular expression) `x`

where `x` is a string (in either single- or double-quotes).

For example, if we want all the columns indicating what was found,

In [18]:
select(stop_df, starts_with("found_"))

        found_contraband found_pistol found_rifle found_assault found_knife
1       FALSE            FALSE        FALSE       FALSE         FALSE
2       FALSE            FALSE        FALSE       FALSE         FALSE
3       FALSE            FALSE        FALSE       FALSE         FALSE
⋮       ⋮                ⋮            ⋮           ⋮             ⋮
999998  FALSE            FALSE        FALSE       FALSE         FALSE
999999  FALSE            FALSE        FALSE       FALSE         FALSE
1000000 FALSE            FALSE        FALSE       FALSE         FALSE
        found_machinegun found_other found_gun found_weapon
1       FALSE            FALSE       FALSE     FALSE
2       FALSE            FALSE       FALSE     FALSE
3       FALSE            FALSE       FALSE     FALSE
⋮       ⋮                ⋮           ⋮         ⋮
999998  FALSE            FALSE       FALSE     FALSE
999999  FALSE            FALSE       FALSE     FALSE
1000000 FALSE            FALSE       FALSE     FALSE

You can see the documentation for `select()` for details.
In general, for any `R` function, you can pull-up the documentation (if one exists) by running `?` followed by the function name.
For example, to see the documentation for `select()` as provided in the `dplyr` package, run:

In [19]:
?dplyr::select

select                  package:dplyr                  R Documentation

_S_u_b_s_e_t _c_o_l_u_m_n_s _u_s_i_n_g _t_h_e_i_r _n_a_m_e_s _a_n_d _t_y_p_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     Select (and optionally rename) variables in a data frame, using a
     concise mini-language that makes it easy to refer to variables
     based on their name (e.g. ‘a:f’ selects all columns from ‘a’ on
     the left to ‘f’ on the right). You can also use predicate
     functions like is.numeric to select variables based on their
     properties.

  _O_v_e_r_v_i_e_w _o_f _s_e_l_e_c_t_i_o_n _f_e_a_t_u_r_e_s:

       Tidyverse selections implement a dialect of R where operators
       make it easy to select variables:

         • ‘:’ for selecting a range of consecutive variables.

         • ‘!’ for taking the complement of a set of variables.

         • ‘&’ and ‘|’ for selecting the intersection or the union of
           two sets of variables.

         • ‘c()’ for combining selections.

       In addition, you can use *selection helpers*. Some helpers
       select specific columns:

         • ‘everything()’: Matches all variables.

         • ‘last_col()’: Select last variable, possibly with an offset.

       These helpers select variables by matching patterns in their
       names:

         • ‘starts_with()’: Starts with a prefix.

         • ‘ends_with()’: Ends with a suffix.

         • ‘contains()’: Contains a literal string.

         • ‘matches()’: Matches a regular expression.

         • ‘num_range()’: Matches a numerical range like x01, x02, x03.

       These helpers select variables from a character vector:

         • ‘all_of()’: Matches variable names in a character vector.
           All names must be present, otherwise an out-of-bounds error
           is thrown.

         • ‘any_of()’: Same as ‘all_of()’, except that no error is
           thrown for names that don't exist.

       This helper selects variables with a function:

         • ‘where()’: Applies a function to all variables and selects
           those for which the function returns ‘TRUE’.


_U_s_a_g_e:

     select(.data, ...)

_A_r_g_u_m_e_n_t_s:

   .data: A data frame, data frame extension (e.g. a tibble), or a lazy
          data frame (e.g. from dbplyr or dtplyr). See _Methods_,
          below, for more details.

     ...: <‘tidy-select’> One or more unquoted expressions separated by
          commas. Variable names can be used as if they were positions
          in the data frame, so expressions like ‘x:y’ can be used to
          select a range of variables.

_V_a_l_u_e:

     An object of the same type as ‘.data’. The output has the
     following properties:

        • Rows are not affected.

        • Output columns are a subset of input columns, potentially
          with a different order. Columns will be renamed if ‘new_name
          = old_name’ form is used.

        • Data frame attributes are preserved.

        • Groups are maintained; you can't select off grouping
          variables.

_M_e_t_h_o_d_s:

     This function is a *generic*, which means that packages can
     provide implementations (methods) for other classes. See the
     documentation of individual methods for extra arguments and
     differences in behaviour.

     The following methods are currently available in loaded packages:
     dbplyr (‘tbl_lazy’), dplyr (‘data.frame’, ‘default’), utils
     (‘list’).

_E_x_a_m_p_l_e_s:

     Here we show the usage for the basic selection operators. See the
     specific help pages to learn about helpers like ‘starts_with()’.

     The selection language can be used in functions like
     ‘dplyr::select()’ or ‘tidyr::pivot_longer()’. Let's first attach
     the tidyverse:

     library(tidyverse)

     # For better printing
     iris <- as_tibble(iris)

     Select variables by name:

     starwars %>% select(height)
     #> # A tibble: 87 x 1
     #>   height
     #>    <int>
     #> 1    172
     #> 2    167
     #> 3     96
     #> 4    202
     #> # ... with 83 more rows

     iris %>% pivot_longer(Sepal.Length)
     #> # A tibble: 150 x 6
     #>   Sepal.Width Petal.Length Petal.Width Species name         value
     #>         <dbl>        <dbl>       <dbl> <fct>   <chr>        <dbl>
     #> 1         3.5          1.4         0.2 setosa  Sepal.Length   5.1
     #> 2         3            1.4         0.2 setosa  Sepal.Length   4.9
     #> 3         3.2          1.3         0.2 setosa  Sepal.Length   4.7
     #> 4         3.1          1.5         0.2 setosa  Sepal.Length   4.6
     #> # ... with 146 more rows

     Select multiple variables by separating them with commas. Note how
     the order of columns is determined by the order of inputs:

     starwars %>% select(homeworld, height, mass)
     #> # A tibble: 87 x 3
     #>   homeworld height  mass
     #>   <chr>      <int> <dbl>
     #> 1 Tatooine     172    77
     #> 2 Tatooine     167    75
     #> 3 Naboo         96    32
     #> 4 Tatooine     202   136
     #> # ... with 83 more rows

     Functions like ‘tidyr::pivot_longer()’ don't take variables with
     dots. In this case use ‘c()’ to select multiple variables:

     iris %>% pivot_longer(c(Sepal.Length, Petal.Length))
     #> # A tibble: 300 x 5
     #>   Sepal.Width Petal.Width Species name         value
     #>         <dbl>       <dbl> <fct>   <chr>        <dbl>
     #> 1         3.5         0.2 setosa  Sepal.Length   5.1
     #> 2         3.5         0.2 setosa  Petal.Length   1.4
     #> 3         3           0.2 setosa  Sepal.Length   4.9
     #> 4         3           0.2 setosa  Petal.Length   1.4
     #> # ... with 296 more rows

  _O_p_e_r_a_t_o_r_s::

       The ‘:’ operator selects a range of consecutive variables:

       starwars %>% select(name:mass)
       #> # A tibble: 87 x 3
       #>   name           height  mass
       #>   <chr>           <int> <dbl>
       #> 1 Luke Skywalker    172    77
       #> 2 C-3PO             167    75
       #> 3 R2-D2              96    32
       #> 4 Darth Vader       202   136
       #> # ... with 83 more rows

       The ‘!’ operator negates a selection:

       starwars %>% select(!(name:mass))
       #> # A tibble: 87 x 11
       #>   hair_color skin_color eye_color birth_year sex   gender homeworld species
       #>   <chr>      <chr>      <chr>          <dbl> <chr> <chr>  <chr>     <chr>
       #> 1 blond      fair       blue            19   male  mascu~ Tatooine  Human
       #> 2 <NA>       gold       yellow         112   none  mascu~ Tatooine  Droid
       #> 3 <NA>       white, bl~ red             33   none  mascu~ Naboo     Droid
       #> 4 none       white      yellow          41.9 male  mascu~ Tatooine  Human
       #> # ... with 83 more rows, and 3 more variables: films <list>, vehicles <list>,
       #> #   starships <list>

       iris %>% select(!c(Sepal.Length, Petal.Length))
       #> # A tibble: 150 x 3
       #>   Sepal.Width Petal.Width Species
       #>         <dbl>       <dbl> <fct>
       #> 1         3.5         0.2 setosa
       #> 2         3           0.2 setosa
       #> 3         3.2         0.2 setosa
       #> 4         3.1         0.2 setosa
       #> # ... with 146 more rows

       iris %>% select(!ends_with("Width"))
       #> # A tibble: 150 x 3
       #>   Sepal.Length Petal.Length Species
       #>          <dbl>        <dbl> <fct>
       #> 1          5.1          1.4 setosa
       #> 2          4.9          1.4 setosa
       #> 3          4.7          1.3 setosa
       #> 4          4.6          1.5 setosa
       #> # ... with 146 more rows

       ‘&’ and ‘|’ take the intersection or the union of two
       selections:

       iris %>% select(starts_with("Petal") & ends_with("Width"))
       #> # A tibble: 150 x 1
       #>   Petal.Width
       #>         <dbl>
       #> 1         0.2
       #> 2         0.2
       #> 3         0.2
       #> 4         0.2
       #> # ... with 146 more rows

       iris %>% select(starts_with("Petal") | ends_with("Width"))
       #> # A tibble: 150 x 3
       #>   Petal.Length Petal.Width Sepal.Width
       #>          <dbl>       <dbl>       <dbl>
       #> 1          1.4         0.2         3.5
       #> 2          1.4         0.2         3
       #> 3          1.3         0.2         3.2
       #> 4          1.5         0.2         3.1
       #> # ... with 146 more rows

       To take the difference between two selections, combine the ‘&’
       and ‘!’ operators:

       iris %>% select(starts_with("Petal") & !ends_with("Width"))
       #> # A tibble: 150 x 1
       #>   Petal.Length
       #>          <dbl>
       #> 1          1.4
       #> 2          1.4
       #> 3          1.3
       #> 4          1.5
       #> # ... with 146 more rows


_S_e_e _A_l_s_o:

     Other single table verbs: ‘arrange()’, ‘filter()’, ‘mutate()’,
     ‘rename()’, ‘slice()’, ‘summarise()’

### Exercise: `select()`

1. Based on the UF-250 form, select the columns from `stop_df` that the officer could have reasonably filled-out _before_ making the stop

In [20]:
# WRITE CODE HERE
# START solution
# 1. 
select(stop_df, 
       # Base information regarding stop:
       id, year, date, time, precinct, location_housing, suspected_crime,
       # Columns specifying stop reason:
       starts_with("stop_reason_"),
       # Suspect demographics:
       starts_with("suspect_"),
       # Officer information:
       starts_with("officer_"))
# END solution

        id      year date       time  precinct location_housing
1        597038 2008 2008-03-16 21:15 105      neither
2       2229402 2011 2011-01-20 02:10 113      neither
3       3498906 2013 2013-03-12 01:45 47       neither
⋮       ⋮       ⋮    ⋮          ⋮     ⋮        ⋮
999998  2840524 2011 2011-12-08 00:10 75       neither
999999  3026282 2012 2012-03-05 22:36 34       neither
1000000 2657973 2011 2011-08-04 08:30 81       transit
        suspected_crime                  suspect_sex suspect_race
1       robbery                          male        black
2       cpw                              male        black
3       cpw                              male        black
⋮       ⋮                                ⋮           ⋮
999998  robbery                          male        black
999999  criminal possession of marihuana male        hispanic
1000000 cpw                              male        black
        suspect_hispanic suspect_age suspect_dob suspect_height suspect_weight
1       FALSE            23          1984-05-31  5.92           185
2       FALSE            30          NA          5.83           180
3       FALSE            35          NA          5.42           160
⋮       ⋮                ⋮           ⋮           ⋮              ⋮
999998  FALSE            17          NA          6.00           170
999999   TRUE            25          1986-03-15  5.75           145
1000000 FALSE            48          1963-06-06  5.75           190
        suspect_hair suspect_eye suspect_build officer_uniform officer_verbal
1       black        brown       thin          FALSE           TRUE
2       black        brown       medium        FALSE           TRUE
3       black        black       medium        FALSE           TRUE
⋮       ⋮            ⋮           ⋮             ⋮               ⋮
999998  brown        brown       thin          FALSE           NA
999999  black        brown       thin           TRUE           NA
1000000 black        brown       medium         TRUE           NA
        officer_shield
1       TRUE
2       TRUE
3       TRUE
⋮       ⋮
999998  TRUE
999999    NA
1000000   NA

### Create new columns (3/5)

Use `mutate(df, ...)` to create new columns, usually as a function of existing columns.

Suppose we wish to create a column called `is_cpw`, indicating whether the `suspected_crime` for each stop was `cpw` (criminal possession of a weapon) or not.
We would write,

In [21]:
mutate(stop_df, is_cpw = (suspected_crime == "cpw"))
# Note that the new column will be the very last column in the data frame

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_eye suspect_build found_gun found_weapon lat  lon
1       105      ⋯ brown       thin          FALSE     FALSE        40.7 -73.7
2       113      ⋯ brown       medium        FALSE     FALSE        40.7 -73.8
3       47       ⋯ black       medium        FALSE     FALSE          NA    NA
⋮       ⋮        ⋱ ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
999998  75       ⋯ brown       thin          FALSE     FALSE        40.7 -73.9
999999  34       ⋯ brown       thin          FALSE     FALSE        40.9 -73.9
1000000 81       ⋯ brown       medium        FALSE     FALSE        40.7 -73.9
        local_hit_rate day      month    is_cpw
1           NA         Sunday   March    FALSE
2       0.0229         Thursday January   TRUE
3           NA         Tuesday  March     TRUE
⋮       ⋮              ⋮        ⋮        ⋮
999998      NA         Thursday December FALSE
999999  0.0366         Monday   March    FALSE
1000000 0.0305         Thursday August    TRUE

Within a single `mutate()` function, you can refer to the new columns you've created in the previous argument.

One, probably useless, yet illustrative example would be computing BMI for each pedestrian who was stopped.

Recall that

$$ \mathrm{BMI} = \frac{\mathrm{weight~(kg)}}{\mathrm{height~(m)}^2}, $$

where weight is in kilograms and height is in meters. 

However, in our data, it seems that weight is in pounds and height is in feet.
Hence we must

1. convert weight in pounds to weight in kilogram (by multiplying 0.45)
1. convert height in feet to height in meters (by multiplying 0.31)
1. compute weight in kilogram divided by square of height in meters

In [22]:
mutate(stop_df,
       weight_kg = suspect_weight * .45,
       height_m = suspect_height * .31,
       BMI = weight_kg / height_m^2)

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ found_gun found_weapon lat  lon   local_hit_rate day
1       105      ⋯ FALSE     FALSE        40.7 -73.7     NA         Sunday
2       113      ⋯ FALSE     FALSE        40.7 -73.8 0.0229         Thursday
3       47       ⋯ FALSE     FALSE          NA    NA     NA         Tuesday
⋮       ⋮        ⋱ ⋮         ⋮            ⋮    ⋮     ⋮              ⋮
999998  75       ⋯ FALSE     FALSE        40.7 -73.9     NA         Thursday
999999  34       ⋯ FALSE     FALSE        40.9 -73.9 0.0366         Monday
1000000 81       ⋯ FALSE     FALSE        40.7 -73.9 0.0305         Thursday
        month    weight_kg height_m BMI
1       March    83.2      1.83     24.7
2       January  81.0      1.81     24.8
3       March    72.0      1.68     25.5
⋮       ⋮        ⋮         ⋮        ⋮
999998  December 76.5      1.86     22.1
999999  March    65.2      1.78     20.5
1000000 August   85.5      1.78     26.9

We could also compute BMI in one fell swoop, without creating the intermediate variables, though that may reduce readability.

In [23]:
mutate(stop_df,
       BMI = (suspect_weight * .45) / (suspect_height * .31)^2)

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_eye suspect_build found_gun found_weapon lat  lon
1       105      ⋯ brown       thin          FALSE     FALSE        40.7 -73.7
2       113      ⋯ brown       medium        FALSE     FALSE        40.7 -73.8
3       47       ⋯ black       medium        FALSE     FALSE          NA    NA
⋮       ⋮        ⋱ ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
999998  75       ⋯ brown       thin          FALSE     FALSE        40.7 -73.9
999999  34       ⋯ brown       thin          FALSE     FALSE        40.9 -73.9
1000000 81       ⋯ brown       medium        FALSE     FALSE        40.7 -73.9
        local_hit_rate day      month    BMI
1           NA         Sunday   March    24.7
2       0.0229         Thursday January  24.8
3           NA         Tuesday  March    25.5
⋮       ⋮              ⋮        ⋮        ⋮
999998      NA         Thursday December 22.1
999999  0.0366         Monday   March    20.5
1000000 0.0305         Thursday August   26.9

### Exercise: `mutate()`

Create a column indicating whether the stop occurred in the morning (prior to 12) or not.
  * This can be created either as a logical column (`TRUE`/`FALSE`), in which case you might name it `is_am`, or
  * by using `if_else` to create a character column of `"am"`/`"pm"`, in which case you might call it `am_pm`
  
Hint: run `?if_else` to read the documentation on how this command works.

In [24]:
# WRITE CODE HERE
# START solution
# A. as a logical column
mutate(stop_df, is_am = hour < 12)

# B. as a character column
mutate(stop_df, am_pm = if_else(hour < 12, "am", "pm"))
# END solution

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_eye suspect_build found_gun found_weapon lat  lon
1       105      ⋯ brown       thin          FALSE     FALSE        40.7 -73.7
2       113      ⋯ brown       medium        FALSE     FALSE        40.7 -73.8
3       47       ⋯ black       medium        FALSE     FALSE          NA    NA
⋮       ⋮        ⋱ ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
999998  75       ⋯ brown       thin          FALSE     FALSE        40.7 -73.9
999999  34       ⋯ brown       thin          FALSE     FALSE        40.9 -73.9
1000000 81       ⋯ brown       medium        FALSE     FALSE        40.7 -73.9
        local_hit_rate day      month    is_am
1           NA         Sunday   March    FALSE
2       0.0229         Thursday January   TRUE
3           NA         Tuesday  March     TRUE
⋮       ⋮              ⋮        ⋮        ⋮
999998      NA         Thursday December  TRUE
999999  0.0366         Monday   March    FALSE
1000000 0.0305         Thursday August    TRUE

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_eye suspect_build found_gun found_weapon lat  lon
1       105      ⋯ brown       thin          FALSE     FALSE        40.7 -73.7
2       113      ⋯ brown       medium        FALSE     FALSE        40.7 -73.8
3       47       ⋯ black       medium        FALSE     FALSE          NA    NA
⋮       ⋮        ⋱ ⋮           ⋮             ⋮         ⋮            ⋮    ⋮
999998  75       ⋯ brown       thin          FALSE     FALSE        40.7 -73.9
999999  34       ⋯ brown       thin          FALSE     FALSE        40.9 -73.9
1000000 81       ⋯ brown       medium        FALSE     FALSE        40.7 -73.9
        local_hit_rate day      month    am_pm
1           NA         Sunday   March    pm
2       0.0229         Thursday January  am
3           NA         Tuesday  March    am
⋮       ⋮              ⋮        ⋮        ⋮
999998      NA         Thursday December am
999999  0.0366         Monday   March    pm
1000000 0.0305         Thursday August   am

### Sorting (4/5)

Use `arrange(df, ...)` to reorder the rows of a data frame by the value of specified columns.
Multiple conditions are arranged from left to right.

In [25]:
arrange(stop_df, date, time)

        id     year frisked searched xcoord  ycoord date       time  hour
1       471569 2007 FALSE   FALSE    1048431 187643 1900-12-31 12:08 12
2       471574 2007  TRUE   FALSE    1020408 238239 1900-12-31 20:20 20
3           54 2007 FALSE   FALSE     951625 171358 2007-01-01 00:05  0
⋮       ⋮      ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  262254 2007 FALSE   FALSE     992062 228791 <NA>       NA    NA
999999   79868 2007  TRUE   FALSE    1002212 193214 <NA>       NA    NA
1000000 624067 2008 FALSE   FALSE     988459 216203 <NA>       NA    NA
        precinct ⋯ suspect_hair suspect_eye suspect_build found_gun
1       113      ⋯ black        brown       medium        FALSE
2       43       ⋯ black        brown       medium        FALSE
3       120      ⋯ black        brown       thin          FALSE
⋮       ⋮        ⋱ ⋮            ⋮           ⋮             ⋮
999998  24       ⋯ black        brown       muscular      FALSE
999999  83       ⋯ black        black       thin          FALSE
1000000 18       ⋯ black        brown       thin          FALSE
        found_weapon lat  lon   local_hit_rate day    month
1       FALSE        40.7 -73.8 NA             Monday December
2       FALSE        40.8 -73.9 NA             Monday December
3       FALSE        40.6 -74.1 NA             Monday January
⋮       ⋮            ⋮    ⋮     ⋮              ⋮      ⋮
999998  FALSE        40.8 -74.0 NA             NA     NA
999999  FALSE        40.7 -73.9 NA             NA     NA
1000000 FALSE        40.8 -74.0 NA             NA     NA

Note that the `NA`s in the column denote missing values, and appear at the end of sorted table.

Use `desc()` around columns that you want to sort in `desc`ending order.

In [26]:
arrange(stop_df, date, desc(time))

        id     year frisked searched xcoord  ycoord date       time  hour
1       471574 2007  TRUE   FALSE    1020408 238239 1900-12-31 20:20 20
2       471569 2007 FALSE   FALSE    1048431 187643 1900-12-31 12:08 12
3          880 2007  TRUE   FALSE     991182 156700 2007-01-01 23:55 23
⋮       ⋮      ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  262254 2007 FALSE   FALSE     992062 228791 <NA>       NA    NA
999999   79868 2007  TRUE   FALSE    1002212 193214 <NA>       NA    NA
1000000 624067 2008 FALSE   FALSE     988459 216203 <NA>       NA    NA
        precinct ⋯ suspect_hair suspect_eye suspect_build found_gun
1       43       ⋯ black        brown       medium        FALSE
2       113      ⋯ black        brown       medium        FALSE
3       62       ⋯ brown        brown       medium        FALSE
⋮       ⋮        ⋱ ⋮            ⋮           ⋮             ⋮
999998  24       ⋯ black        brown       muscular      FALSE
999999  83       ⋯ black        black       thin          FALSE
1000000 18       ⋯ black        brown       thin          FALSE
        found_weapon lat  lon   local_hit_rate day    month
1       FALSE        40.8 -73.9 NA             Monday December
2       FALSE        40.7 -73.8 NA             Monday December
3       FALSE        40.6 -74.0 NA             Monday January
⋮       ⋮            ⋮    ⋮     ⋮              ⋮      ⋮
999998  FALSE        40.8 -74.0 NA             NA     NA
999999  FALSE        40.7 -73.9 NA             NA     NA
1000000 FALSE        40.8 -74.0 NA             NA     NA

### Aggregating (5/5)

Use `summarize(df, ...)` to aggregate multiple rows into a single row. Unlike `mutate()`, functions that are used in `summarize()` must return a single value (i.e., "aggregate" the provided vector)

For example, to find the min, mean, and max height of all suspects,

In [27]:
summarize(stop_df,
          min_height = min(suspect_height),
          avg_height = mean(suspect_height),
          max_height = max(suspect_height))

  min_height avg_height max_height
1 3          5.72       7.92

`dplyr` also provides a special function `n()` which will evaluate to the number of rows within a `dplyr` verb.

For example, to count how many stops (rows) there are in total,

In [28]:
summarize(stop_df, N = n())

  N
1 1000000

### Exercise: `summarize()`

For `stop_df`, find 

* Average `suspect_weight`,
* Median `suspect_weight`,
* Standard deviation (`sd`) of `suspect_weight`, and
* Number of all stops

Hint: Many numerical summaries of `suspect_weight` (e.g., `mean`) will return the value `NA`, because some of the entries in the vector are missing. To remove these missing entries before computing the mean, pass in the argument `na.rm=TRUE` to the `mean` function. This argument can be used in many numerical functions, including `mean`, `median`, and `sd`.

In [29]:
# WRITE CODE HERE
# START solution
summarize(stop_df,
          avg_weight = mean(suspect_weight, na.rm=TRUE),
          med_weight = median(suspect_weight, na.rm=TRUE),
          sd_weight = sd(suspect_weight, na.rm=TRUE),
          N = n())
# END solution

  avg_weight med_weight sd_weight N
1 169        170        30.2      1000000

### Grouping (Split-apply-combine)

Now that we've covered the five core verbs, we should be able to manipulate data to our heart's desire, yes?

Then, how about:

* The number of stops for each `suspect_race`?
* Proportion of stops in each precinct that resulted in recovery of a weapon?
* Number of stops for each race group by `suspected_crime`?

As an example, let's just consider the number of stops for each `suspect_race`.

A natural, but _**tedious**_ way to compute this would look something like this:

In [30]:
# NOTE: Code in this cell is intended to be an example of a BAD way to compute this.
#       This is purely for illustrative purposes, and should NEVER EVER be re-used, in any context. Never.
white_stops <- filter(stop_df, suspect_race == "white")
black_stops <- filter(stop_df, suspect_race == "black")
hispanic_stops <- filter(stop_df, suspect_race == "hispanic")

N_whites <- summarize(white_stops, N = n())
N_blacks <- summarize(black_stops, N = n())
N_hispanics <- summarize(hispanic_stops, N = n())

c(white = N_whites$N, black = N_blacks$N, hispanic = N_hispanics$N)

   white    black hispanic
   98077   522449   311440

This style of code can easily get out of hand, and would be a nightmare to maintain! 
For example, what happens if we get a new dataset that includes 8 different race categories? 
(Note: In this specific example, we could alternatively use the `table` command, as we did at the very beginning of this notebook, but that approach doesn't work in the more complicated examples we consider below.)

As horrible as the above code is, it is useful in highlighting a common pattern that emerges when manipulating data:

1. **Split**: The data are split into smaller pieces of data, according to one (or more) column. 
   In this case, we've split the data by the `suspect_race` column.
1. **Apply**: Some operation is applied to each of the smaller pieces.
   In this case, we've simply counted the number of rows of each piece using `summarize()` and `n()`.
1. **Combine**: The results of the previous **apply** are combined to some final data structure.
   In the above case, for simplicity, we've combined the result as a vector; but in practice we usually want to keep everything in the form of a data frame.

This pattern in data manipulation is so common, that there is a `dplyr` verb for it. 
This is the `group_by` verb.

On it's own, `group_by` makes no visible changes to a data frame, other than marking the data frame as being "grouped".
The difference is only made apparent when we apply some other verb to a grouped data frame.

Note that none of the `dplyr` verbs make any changes to the original data frame! This is intentional. 
So, for now, we need to save the "grouped" data as a new variable for our changes to have effect (but we'll see a more convenient approach to this later).

In [31]:
stops_by_race <- group_by(stop_df, suspect_race)

# Note that the two data frames, on the surface, seem identical.
stop_df
stops_by_race

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_hair suspect_eye suspect_build found_gun
1       105      ⋯ black        brown       thin          FALSE
2       113      ⋯ black        brown       medium        FALSE
3       47       ⋯ black        black       medium        FALSE
⋮       ⋮        ⋱ ⋮            ⋮           ⋮             ⋮
999998  75       ⋯ brown        brown       thin          FALSE
999999  34       ⋯ black        brown       thin          FALSE
1000000 81       ⋯ black        brown       medium        FALSE
        found_weapon lat  lon   local_hit_rate day      month
1       FALSE        40.7 -73.7     NA         Sunday   March
2       FALSE        40.7 -73.8 0.0229         Thursday January
3       FALSE          NA    NA     NA         Tuesday  March
⋮       ⋮            ⋮    ⋮     ⋮              ⋮        ⋮
999998  FALSE        40.7 -73.9     NA         Thursday December
999999  FALSE        40.9 -73.9 0.0366         Monday   March
1000000 FALSE        40.7 -73.9 0.0305         Thursday August

        id      year frisked searched xcoord  ycoord date       time  hour
1        597038 2008 TRUE    FALSE    1053946 197411 2008-03-16 21:15 21
2       2229402 2011 TRUE    FALSE    1040970 188491 2011-01-20 02:10  2
3       3498906 2013 TRUE    FALSE         NA     NA 2013-03-12 01:45  1
⋮       ⋮       ⋮    ⋮       ⋮        ⋮       ⋮      ⋮          ⋮     ⋮
999998  2840524 2011 TRUE    FALSE    1017479 181524 2011-12-08 00:10  0
999999  3026282 2012 TRUE    FALSE    1003466 250306 2012-03-05 22:36 22
1000000 2657973 2011 TRUE     TRUE    1003927 186763 2011-08-04 08:30  8
        precinct ⋯ suspect_hair suspect_eye suspect_build found_gun
1       105      ⋯ black        brown       thin          FALSE
2       113      ⋯ black        brown       medium        FALSE
3       47       ⋯ black        black       medium        FALSE
⋮       ⋮        ⋱ ⋮            ⋮           ⋮             ⋮
999998  75       ⋯ brown        brown       thin          FALSE
999999  34       ⋯ black        brown       thin          FALSE
1000000 81       ⋯ black        brown       medium        FALSE
        found_weapon lat  lon   local_hit_rate day      month
1       FALSE        40.7 -73.7     NA         Sunday   March
2       FALSE        40.7 -73.8 0.0229         Thursday January
3       FALSE          NA    NA     NA         Tuesday  March
⋮       ⋮            ⋮    ⋮     ⋮              ⋮        ⋮
999998  FALSE        40.7 -73.9     NA         Thursday December
999999  FALSE        40.9 -73.9 0.0366         Monday   March
1000000 FALSE        40.7 -73.9 0.0305         Thursday August

In [32]:
# But we can see a difference when applying, for example, a summarize
summarize(stop_df, N = n())

  N
1 1000000

In [33]:
summarize(stops_by_race, N = n())

`summarise()` ungrouping output (override with `.groups` argument)

  suspect_race    N
1 asian            31781
2 black           522449
3 native american   4015
⋮ ⋮               ⋮
5 white           98077
6 other           26082
7 NA               6156

As shown in the simple example above, when a `dplyr` verb is applied to a "grouped" data frame,
`dplyr` internally **splits**, **applies**, and **combines** the data, finally returning results for
_each of the unique values that are found in the columns by which the data frame is grouped_.

This can be a lot to process if it's the first time you've seen this. 
But once you get used to it (via trying a bunch of manipulation tasks and seeing some more examples), you'll find it extremely convenient and powerful.

Let's try answering the other questions we started this section with.

* Proportion of stops in each precinct that resulted in recovery of a weapon?

In [34]:
stops_by_precinct <- group_by(stop_df, precinct)

summarize(stops_by_precinct, 
          # Note that below, we compute the mean of a logical (TRUE/FALSE) column
          #   this is a common "trick" used in R to compute proportions, taking advantage of
          #   the fact that a TRUE value is equivalent to a 1 and FALSE is equivalent to a 0 in R
          prop_weapons_found = mean(found_weapon))

`summarise()` ungrouping output (override with `.groups` argument)

   precinct prop_weapons_found
1  1        0.0161
2  10       0.0207
3  100      0.0131
⋮  ⋮        ⋮
75 9        0.02235
76 90       0.00966
77 94       0.01455

* Number of stops for each race group by `suspected_crime` type?

To find this, we first notice that the data must be split by two columns, `suspect_race` _and_ `suspected_crime`.
This is also supported by `group_by`. In fact, you can have as many grouping variables as you'd like, as long as it makes sense in the context.

In [35]:
stops_by_race_and_crime <- group_by(stop_df, suspect_race, suspected_crime)
summarize(stops_by_race_and_crime, N = n())

`summarise()` regrouping output by 'suspect_race' (override with `.groups` argument)

    suspect_race suspected_crime                   N
1   asian        aggravated assault                 2
2   asian        aggravated harassment             15
3   asian        arson                              7
⋮   ⋮            ⋮                                 ⋮
536 NA           unlawfully dealing with fireworks 4
537 NA           vehicular assault                 1
538 NA           NA                                1

### Exercise: `group_by()`

For `stop_df`, calculate the proportion of people who are frisked (`frisked`) and arrested (`arrested`) for each race group.

In [36]:
# WRITE CODE HERE
# START solution
race_group <- group_by(stop_df, suspect_race)
summarize(race_group, 
          frisk_rate = mean(frisked),
          arrest_rate = mean(arrested)
         )
# END solution

`summarise()` ungrouping output (override with `.groups` argument)

  suspect_race    frisk_rate arrest_rate
1 asian           0.469      0.0643
2 black           0.571      0.0609
3 native american 0.468      0.0493
⋮ ⋮               ⋮          ⋮
5 white           0.439      0.0662
6 other           0.515      0.0487
7 NA              0.471      0.0611

### Multiple (chained) operations

As we've briefly seen above, we would often like to apply multiple operations (verbs) to a data frame.
However, by design, verbs do not save intermediate changes to the original data frame, so for each operation we would have to assign the result to a new data frame.

Even for a reasonable number of operations, this can get quite messy (i.e., we'd end up with so many names and data frames that we only use as intermediate steps).

Consider the following query:

* For each suspected crime type, what is the proportion of stops for each race group?

We can think of finding the answer in multiple steps:

1. group by `suspected_crime` and `suspect_race`
1. find the number of stops for each of the groups in the previously grouped data frame
1. with the computed stops for each crime type/race pair, re-group by only `suspected_crime`
1. create a new column with the proportion of stops for each race group (for that suspected crime) by dividing the number of stops in each row by the total for that suspected crime.

Using the current method of saving all intermediate results, the implementation would look something like this:

In [37]:
# NOTE: Code in this cell is intended to be an example of a BAD implementation.
#       While this implementation is acceptable, it is intended for illustrative purposes, 
#       and is best avoided.
stops_by_crime_and_race <- group_by(stop_df, suspected_crime, suspect_race)
counts_by_crime_and_race <- summarize(stops_by_crime_and_race, N = n())
regroup_by_crime <- group_by(counts_by_crime_and_race, suspected_crime)
mutate(regroup_by_crime, prop = N / sum(N))

`summarise()` regrouping output by 'suspected_crime' (override with `.groups` argument)

    suspected_crime        suspect_race N prop
1   abandonment of a child black        9 0.6429
2   abandonment of a child hispanic     4 0.2857
3   abandonment of a child white        1 0.0714
⋮   ⋮                      ⋮            ⋮ ⋮
536 NA                     white        3 0.2143
537 NA                     other        1 0.0714
538 NA                     NA           1 0.0714

The above code is bad for a multiple reasons. Among others, it's

* creating a lot of unnecessary intermediate results that will not be used again
* difficult to read, if you don't already know what the end goal is (e.g., your eyes have to wander left-to-right-to-left a few times to see what's going on)!

A sophisticated, yet quite simple, solution to this problem is the introduction of `%>%`, also called the "pipe operator".

`%>%` is a _binary operator_ (much like `+` or `-`) which, in words, takes the result of the left-hand side, and uses it as the first argument on the right hand side. 
This may be confusing at first, but it makes a lot of sense in the context of `dplyr` _verbs_. Recall, a _verb_ in `dplyr` is any function that _returns a data frame_ (LHS) and _takes a data frame as its first argument_ (RHS).

If further notation is helpful, one could also write the `%>%` as
```
f(x) %>% g(y) = g(f(x), y)
```
which, depending on your background, could be clarifying or more confusing!

What this means from a practical standpoint, however, is that we no longer need to _save_ intermediate results just to use them in the next verb. 
Instead, we can use `%>%` to send results from a verb down a "pipe" to the next verb.
Consider our previous example, which involved four verbs, with three intermediate steps.
Using `%>%`, the same result can now be achieved in a (conceptually) single line:

In [38]:
stop_df %>%
    group_by(suspected_crime, suspect_race) %>%
    summarize(N = n()) %>%
    group_by(suspected_crime) %>%
    mutate(prop = N / sum(N))

`summarise()` regrouping output by 'suspected_crime' (override with `.groups` argument)

    suspected_crime        suspect_race N prop
1   abandonment of a child black        9 0.6429
2   abandonment of a child hispanic     4 0.2857
3   abandonment of a child white        1 0.0714
⋮   ⋮                      ⋮            ⋮ ⋮
536 NA                     white        3 0.2143
537 NA                     other        1 0.0714
538 NA                     NA           1 0.0714

Note the intentional style of (1) starting from the data frame (instead of a verb that explicitly includes the data frame) and (2) keeping each verb on its own line. 
This not only makes it easier to read, but also easier to maintain and modify.

### Exercise: Chaining in `dplyr`

1. Find the distribution of suspected crimes for each race group
(e.g., what proportion of white, Black, Hispanic, etc., pedestrian stops were due to suspicion of `cpw`?)

2. Using the result from the above exercise, find the suspected crimes that account for more than 10% of stops in all race groups.

hint: `all(logical_vector)` will return `TRUE` if all values in `logical_vector` are `TRUE`

In [39]:
# WRITE CODE HERE
# START solution
# 1. 
suspected_crime_by_race <- stop_df %>%
    group_by(suspected_crime, suspect_race) %>%
    summarize(N = n()) %>%
    group_by(suspect_race) %>%
    mutate(proportion = N / sum(N))
suspected_crime_by_race

# 2. 
suspected_crime_by_race %>%
    group_by(suspected_crime) %>%
    filter(all(proportion > 0.1))
# END

`summarise()` regrouping output by 'suspected_crime' (override with `.groups` argument)

    suspected_crime        suspect_race N proportion
1   abandonment of a child black        9 1.72e-05
2   abandonment of a child hispanic     4 1.28e-05
3   abandonment of a child white        1 1.02e-05
⋮   ⋮                      ⋮            ⋮ ⋮
536 NA                     white        3 3.06e-05
537 NA                     other        1 3.83e-05
538 NA                     NA           1 1.62e-04

   suspected_crime suspect_race    N      proportion
1  cpw             asian             3564 0.112
2  cpw             black           157501 0.301
3  cpw             native american    591 0.147
⋮  ⋮               ⋮               ⋮      ⋮
12 robbery         white           10386  0.106
13 robbery         other            4297  0.165
14 robbery         NA                958  0.156

## End notes

There are many, MANY more verbs that we simply did not have the time to cover here, but are immensely useful. 
Some examples are:

* `rename(df, ...)`: rename columns
* `slice(df, ...)`: select rows of a data frame by index, instead of some condition
* `top_n(df, N, col)`: retrieve the top N rows for values in some specified column

You are highly recommended to explore more. One great resource for learning about `tidyverse` and using it to work with data is Hadley Wickham's online book: [R for Data Science](https://r4ds.had.co.nz/). 

Hadley Wickham is also the original author for many of the packages in `tidyverse`. In fact, in the "early days" (circa 2016), before the word `tidyverse` was created, the collection of Hadley Wickham's `R` packages were unofficially referred to as the `hadleyverse`!